feat: add saving uart mode to setinterface and add to init script

diff --git a/base-system/setinterface b/base-system/setinterface
--- a/base-system/setinterface
+++ b/base-system/setinterface
@@ -34,6 +34,7 @@ UART_GPIO_11=(459 460 461 462)
 RS232_MODE=0
 RS485_MODE=1
 RS422_MODE=2
+UNKNOWN_MODE=9
 RS232_GPIO_MODE=(1 1 0 0)
 RS485_GPIO_MODE=(0 0 0 1)
 RS422_GPIO_MODE=(0 0 1 0)
@@ -42,7 +43,10 @@ RS232_MODE_STR="Now setting is RS232 mode"
 RS485_MODE_STR="Now setting is RS485-2W mode"
 RS422_MODE_STR="Now setting is RS422/RS485-4W mode"
 
+UARTCONF="/etc/moxa-configs/setinterface.conf"
+
 declare CUR_UART
+declare CUR_MODE
 
 PCBA_SERIAL=0
 PCBA_DEFAULT=0
@@ -73,15 +77,47 @@ check_root_user() {
 }
 
 usage() {
-	echo -ne "Usage: /usr/bin/setinterface device-node [interface-no]\n"
+	echo -ne "Usage:  setinterface [OPTION]...\n"
+	echo -ne " [device-node] [interface-no],\tset or get UART mode for sepcific port\n"
+	echo -ne "\t\t\t\te.g. set mode: setinterface /dev/ttyM0 0\n"
+	echo -ne "\t\t\t\te.g. get mode: setinterface /dev/ttyM0\n"
 	echo -ne "\tdevice-node     - /dev/ttyMn, n = [0:${MAX_GPIO_PORT_NUM}]\n"
 	echo -ne "\tinterface-no    - following:\n"
 	echo -ne "\tnone - to view now setting\n"
-	echo -ne "\t0 - set to RS232 interface\n"
-	echo -ne "\t1 - set to RS485-2W interface\n"
-	echo -ne "\t2 - set to RS422/RS485-4W interface\n"
-	echo -ne "\n"
+	echo -ne "\t\t0 - set to RS232 interface\n"
+	echo -ne "\t\t1 - set to RS485-2W interface\n"
+	echo -ne "\t\t2 - set to RS422/RS485-4W interface\n"
+	echo -ne " -h,\t show this help page\n"
+	echo -ne " -s,\t save current UART mode to file\n"
 	exit 0
+}
+
+save_status() {
+	echo "Save current status to $UARTCONF ..."
+	if [[ ! -f "$UARTCONF" ]]; then
+		echo "setinterface config file $UARTCONF is not existed. Exit."
+		exit 3
+	fi
+
+	index=0
+	for index in `seq 0 $MAX_GPIO_PORT_NUM`
+	do
+		get_port_mode $index
+		echo "Get port $index mode is $CUR_MODE"
+		eval "sed -i -e '/#/!s/PORT${index}=[0-9]/PORT${index}=${CUR_MODE}/g' $UARTCONF"
+	done
+
+	exit 0
+}
+
+get_port_mode() {
+	port=$1
+	if [ $port -ge 0 ] && [ $port -le $MAX_GPIO_PORT_NUM ]; then
+		exp_board_uart_mode $port
+	else
+		echo "Target device port $1 is invalid. Exit."
+		exit -1
+	fi
 }
 
 exp_board_uart_mode() {
@@ -92,7 +128,7 @@ exp_board_uart_mode() {
 	if [ -z "$mode" ]; then
 		# get mode
 		exp_board_get_uart_mode
-		exit 0
+		return
 
 	# set mode
 	elif [ x"$mode" == x"$RS232_MODE" ]; then
@@ -122,6 +158,7 @@ exp_board_get_uart_mode() {
 	cmp_result=$(diff_array pin_array[@] RS232_GPIO_MODE[@])
 	if [ x"${cmp_result}" == x"0" ]; then
 		echo $RS232_MODE_STR
+		CUR_MODE=$RS232_MODE
 		return
 	fi
 
@@ -129,6 +166,7 @@ exp_board_get_uart_mode() {
 	cmp_result=$(diff_array pin_array[@] RS485_GPIO_MODE[@])
 	if [ x"${cmp_result}" == x"0" ]; then
 		echo $RS485_MODE_STR
+		CUR_MODE=$RS485_MODE
 		return
 	fi
 
@@ -136,10 +174,12 @@ exp_board_get_uart_mode() {
 	cmp_result=$(diff_array pin_array[@] RS422_GPIO_MODE[@])
 	if [ x"${cmp_result}" == x"0" ]; then
 		echo $RS422_MODE_STR
+		CUR_MODE=$RS422_MODE
 		return
 	fi
 
-	echo "Cannot recognize current mode. Exit."
+	echo "Cannot recognize current mode."
+	CUR_MODE=$UNKNOWN_MODE
 }
 
 exp_board_set_uart_mode() {
@@ -224,11 +264,16 @@ gpio_init()
 }
 
 main() {
+	check_root_user
+
 	if [ x"$1" == x"-h" ]; then
 		usage
 	fi
 
-	check_root_user
+	if [ x"$1" == x"-s" ]; then
+		save_status
+	fi
+
 	get_pcba_serial
 
 	port=${1##*/dev/ttyM}
@@ -256,7 +301,6 @@ fi
 
 if [ $# -eq 0 ] || [ $# -gt 2 ]; then
 	usage
-	exit -1
 fi
 
 main $1 $2
